### ISSUE TITLE
not working on nextcloud 11.0.5

### ISSUE THREAD

**Issue by zoigecyb** [ZeXtras/zimbra-drive#10] opened 2017-09-24 15:16 UTC
hello. i tried to install zimbradrive on nextcloud 11.0.5, 12.0.2 and it's not working. i fill all fields as in installation manual, but the test result is:

[FAILED] Enabled Zimbra's users test : Zimbra's users are disabled.

[FAILED] Enabled Zimbra's user login : Zimbra Drive authentication is disabled.

[FAILED] Is server url set test : The server url is not set.

[FAILED] Is server port set test : The server port is not set.

[FAILED] Zimbra host connection test :

[FAILED] Zimbra authentication page connection test : Impossible to connect to Zimbra ( response http code: 0; url = https://: )

[FAILED] Zimbra Drive extension connection test : Impossible to connect to Zimbra Drive extension (response http code: 0 )

zimbradrive latest for owncloud 11 from nextcloud official store

**Comment by ZxUgoPadoan** [comment] 2017-09-28 08:57
Hello @zoigecyb and thank you for the issue report.
I can't reproduce the issue.
Can you send to ext.services@zextras.com the Nextcloud log file?
If you reload the page, Zimbra Drive fields remains filled?

**Comment by zoigecyb** [comment] 2017-10-30 15:19
after reloading page fields are empty. log file i've sent.

**Comment by jamesh76** [comment] 2017-12-09 02:45
@zoigecyb 
I ran into this problem sometime back.  You need to use Chrome to fill in the form.  It does not save if you do it in Firefox.  I had this problem with two completely separate installations, client, server, everything was separate.  I don't know what the cause is. 

Developers: this can be reproduced by using Firefox to attempt to configure the zimbradrive extension.  If you need further details of my setups, to reproduce this, please let me know.  It is repeatable for me.

**Comment by ZxUgoPadoan** [comment] 2018-01-09 09:37
The bug should be fixed in the new release (v. 0.8.18), let me know if the problem persists.

**Comment by jamesh76** [comment] 2018-01-14 08:12
Confirmed, now working as expected for me! 

Thanks, 
James

**Closed** 2018-01-14 16:14 UTC
