### ISSUE TITLE
Not working NextCloud 12

### ISSUE THREAD

**Issue by patn03** [ZeXtras/zimbra-drive#13] opened 2017-10-11 17:42 UTC
Looks like auth and integration is broken after updating to NextCloud 12 and 8.15 Zimbra Drive
I'm able to get the same errors in that forum topic. Can't login or add files

https://forums.zimbra.org/viewtopic.php?f=58&t=62868
https://bugzilla.zimbra.com/show_bug.cgi?id=108092

Pat

**Comment by ChristophBusold** [comment] 2017-11-04 14:14
Playing around a bit with the issue I find that it is caused by a mismatch in zimbra-extension (branch 8.7.11): CloudUtils.java (used by GetAllFoldersHdlr.java) sends requests with Zimbra account ID, UploadFileHttpHandler.java instead with email address. Latter is getting rejected during authentication with zimbra-extension, which causes file uploads to fail.

This could be fixed in zimbra-drive app (by looking up and replacing email with account ID), but I think there is a more fundamental problem underneath the covers. The zimbra-extension and zimlet are updated together with ZCS, but the zimbra-drive app via Nextcloud app store. If there is a dependency between zimbra-drive app and zimbra-extension/zimlet, this will eventually break when users update their app but not ZCS. In my opinion there needs to be compatibility (at least in some direction) between zimbra-extension and Nextcloud app. What do ZeXtras folks think @bud-mo?

**Comment by ZxUgoPadoan** [comment] 2018-01-12 13:31
@patn03 The bug should be fixed in the new release (Zimbra Drive app v. 0.8.18), let me know if the problem persists.

**Comment by ChristophBusold** [comment] 2018-01-13 16:19
@ZxUgoPadoan The fix is in the Zimbra extension, not the Nextcloud app, right? At least for me 0.8.18 still has the same issue with both 8.7.11 and 8.8.5.

**Comment by bud-mo** [comment] 2018-01-15 14:04
@ChristophBusold We are focused on maintain the backward compatibility between the oc/nc app and the zimbra extension. 
We have made a bunch of tests with Zimbra 8.8.5 and the latest version of Zimbra Drive which can be found in the `master` branch in conjunction with the OC app v0.8.18 and it seems to work great.
Please can You provide to @ZxUgoPadoan more details on how to reproduce the issue?
We are not sure on which condition are You running on.

**Comment by ChristophBusold** [comment] 2018-01-15 23:07
Apologies, it was a misconfiguration on my side, it actually works now with Zimbra 8.8.6 and Nextcloud app 0.8.18.

**Closed** 2018-02-21 16:13 UTC
